# Generated by Django 3.0.4 on 2020-03-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='phone',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='phone',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
