# Generated by Django 3.0.4 on 2020-03-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notp', '0003_auto_20200326_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='zip',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
