# Generated by Django 3.0.4 on 2020-03-28 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notp', '0004_donor_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 13, 9, 44, 305041), verbose_name='date joined'),
        ),
    ]
