# Generated by Django 3.0.4 on 2020-03-28 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notp', '0006_auto_20200328_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
