# Generated by Django 3.0.4 on 2020-03-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notp', '0007_auto_20200328_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='donor',
        ),
        migrations.AddField(
            model_name='recipient',
            name='zip',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
