# Generated by Django 3.0.4 on 2020-03-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notp', '0008_auto_20200328_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='phone',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
