# Generated by Django 3.0.4 on 2020-03-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notp', '0009_auto_20200328_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
