# Generated by Django 3.0.4 on 2020-03-29 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notp', '0010_auto_20200328_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='zip',
            new_name='zipcode',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
