# Generated by Django 3.0.4 on 2020-03-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notp', '0011_auto_20200328_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='phone',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
